// Routines
export const FETCH_ROUTINE_REQUEST = 'FETCH_ROUTINE_REQUEST'
export const FETCH_ROUTINE_SUCCESS = 'FETCH_ROUTINE_SUCCESS'
export const FETCH_ROUTINE_ERROR = 'FETCH_ROUTINE_ERROR'

export const UPDATE_ROUTINE_REQUEST = 'UPDATE_ROUTINE_REQUEST'
export const UPDATE_ROUTINE_SUCCESS = 'UPDATE_ROUTINE_SUCCESS'
export const UPDATE_ROUTINE_ERROR = 'UPDATE_ROUTINE_ERROR'

export const DELETE_ROUTINE_REQUEST = 'DELETE_ROUTINE_REQUEST'
export const DELETE_ROUTINE_SUCCESS = 'DELETE_ROUTINE_SUCCESS'
export const DELETE_ROUTINE_ERROR = 'DELETE_ROUTINE_ERROR'

// Sets
export const DELETE_SET = 'DELETE_SET'

export const ADD_UNSAVED_SET = 'ADD_UNSAVED_SET'
